// AUTOGENERATED FROM PICO_CONFIG_HEADER_FILES and then PICO_<PLATFORM>_CONFIG_HEADER_FILES
// DO NOT EDIT!


// based on PICO_CONFIG_HEADER_FILES:

#include <boards/pico.h>

// based on PICO_RP2040_CONFIG_HEADER_FILES:

#define LIB_CMSIS_CORE		0				// added by DC
#include <cmsis/rename_exceptions.h>

// End
